<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    public function countAll($minYear, $maxYear) {
//        $query = $this->createQueryBuilder("m")->select("count(m)")->getQuery();
//        $count = $query->getSingleScalarResult();
//        return $count;
        
        $queryBuilder = $this->createQueryBuilder("m")
                ->select("count(m)");
        if(!empty($minYear)){
            $queryBuilder->andWhere("m.year >= :minYear")->andWhere("m.year <= :maxYear");
            $queryBuilder->setParameter("minYear", $minYear)->setParameter("maxYear", $maxYear);
        }
        $query = $queryBuilder->getQuery();
        $count = $query->getSingleScalarResult();
        return $count;
    }
    
    public function findByYear($minYear, $maxYear, $page=1, $numPerPage){
        
        $offset = ($page - 1) * $numPerPage;
        
        $queryBuilder = $this->createQueryBuilder("m")
                ->select("m");
        if(!empty($minYear)){
            $queryBuilder->andWhere("m.year >= :minYear")->andWhere("m.year <= :maxYear");
            $queryBuilder->setParameter("minYear", $minYear)->setParameter("maxYear", $maxYear);
        }
            
        $queryBuilder->setMaxResults($numPerPage);
        $queryBuilder->setFirstResult($offset);
        $query = $queryBuilder->getQuery();
        $search = $query->getResult();
        
         return $search;
    }
}
